module.exports = {

    CART_HAS_ISSUES: "CART_HAS_ISSUES",

    OUT_OF_STOCK: "OUT_OF_STOCK",

    INACTIVE_MEDICINE: "INACTIVE_MEDICINE",

    INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

    MEDICINE_REMOVED: "MEDICINE_REMOVED",

    PRESCRIPTION_REQUIRED: "PRESCRIPTION_REQUIRED",

    PRICE_CHANGED: "PRICE_CHANGED"

};